language: node_js
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - js-given/node_modules
    - documentation/node_modules
    - examples/jest-es2015/node_modules
    - examples/jest-typescript/node_modules
    - examples/jest-es2015-flow/node_modules
    - examples/mocha-es5/node_modules
node_js:
  - "6"
  - "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "gem install asciidoctor"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - travis_wait 45 yarn
after_success:
  - 'cat ./js-given/coverage/lcov.info | ./node_modules/.bin/coveralls'
